use_frameworks!
platform :ios, '11.3'

target 'SSegmentRecordingView_Example' do
  pod 'SSegmentRecordingView', :path => '../'

  target 'SSegmentRecordingView_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

    pod 'Quick', '~> 2.2'
    pod 'Nimble', '~> 8.0'
    pod 'Nimble-Snapshots' , '~> 8.1'

  end
end
