use_frameworks!
platform :ios, '11.3'

target 'SSegmentRecordingView_Example' do
  pod 'SSegmentRecordingView', :path => '../'

  target 'SSegmentRecordingView_Tests' do
    inhibit_all_warnings!
    inherit! :search_paths

    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.1'
    pod 'FBSnapshotTestCase' , '~> 2.1.4'
    pod 'Nimble-Snapshots' , '~> 6.9.0'

  end
end
